name: Build macOS App

on:
  workflow_dispatch: # allows manual run from GitHub UI

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build mac app
        run: npm run build:mac

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/*
